### ISSUE TITLE
Iniciar proyecto con main basico

### ISSUE THREAD

**Issue by Garciat** [upsa-bd2-2015/test#2]
El main debe retornar condicion de exito (0).

**Comment by alexpizarroj** [comment]
Garcia, y dis not don

**Comment by Garciat** [comment]
a4b7e83caa2e09ae4d5da2c75065ec52f8bf800a

@alexpizarroj hacer review del codigo y cerrar ticket.

**Comment by alexpizarroj** [comment]
Well done.
